name: sistema_registro
description: Console Application criado como exemplo de solução para o desafio.
version: 1.0.0

environment:
  sdk: '>=2.19.0-49.0.dev <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  intl: ^0.17.0
  uuid: ^3.0.6
